{{- if .Values.secrets.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secrets.providerClass }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.secretName }}"
        objectType: "secretsmanager"
        jmesPath: 
            - path: "db_password"
              objectAlias: "DB_PASSWORD"
            - path: "rabbitmq_password"
              objectAlias: "RABBITMQ_PASSWORD"
{{- end }}
