apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-provider
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "prod/audio-app/secrets"
        objectType: "secretsmanager"
        jmesPath: 
            - path: "db_password"
              objectAlias: "DB_PASSWORD"
            - path: "rabbitmq_password"
              objectAlias: "RABBITMQ_PASSWORD"
